export const projects = [
   {
      id: 1,
      title: 'Todo App',
      topics: 'React JS Hooks, React Icons',
      image: './images/Todo-app.png',
      link: 'https://todo-app-red-black.netlify.app/',
   },
   {
      id: 2,
      title: 'Simple Dictionary',
      topics: 'Vanila JS, Sounds, API',
      image: './images/dictionary.png',
      link: 'https://adastra97.github.io/dictionary-api/',
   },
   {
      id: 3,
      title: 'My First Landing',
      topics: 'Pug, Scss, Slick Slider, Grid',
      image: './images/landing.png',
      link: 'https://adastra97.github.io/examWork/public/',
   },
   {
      id: 4,
      title: 'Aim Training',
      topics: 'Html, CSS, Vanilla JS',
      image: './images/aim-training.png',
      link: 'https://adastra97.github.io/Aim-training/',
   },
   {
      id: 5,
      title: 'Calculator',
      topics: 'React Hook Reducer, Tailwind CSS',
      image: './images/calculator.png',
      link: 'https://calculator-syrniki.netlify.app/',
   },
   {
      id: 6,
      title: 'Handmade Shop',
      topics: 'HTML, CSS, Vanilla JS, hash routing',
      image: './images/handmade-shop.png',
      link: 'https://handmade-shop-api.netlify.app/',
   },
   {
      id: 7,
      title: 'My game "A way at home"',
      topics: 'HTML, CSS, Phaser JS, Vanilla JS, Tiled, Sounds',
      image: './images/game.png',
      link: 'https://way-at-home.netlify.app/',
   },
   {
      id: 8,
      title: 'Movie APP',
      topics: 'Pug, SCSS, Vanilla JS, Firebase, SweetAlert, Swiper',
      image: './images/movie-app.png',
      link: 'https://entertainment-web-app-qwe.netlify.app/',
   },
   {
      id: 9,
      title: 'Password Generator',
      topics: 'HTML, CSS, Vanilla JS, map collection',
      image: './images/pass-generator.png',
      link: 'https://adastra97.github.io/password-generator/',
   },
];